### ISSUE TITLE
I can't connect the CMS to my Localhost.

### ISSUE THREAD

**Issue by Egmo23** [LUNIServer/UniverseLauncher#5]
I can't connect the CMS to my Localhost.

**Comment by Egmo23** [comment]
Connect Error (2002) No such file or directory

is the error that shows up when I do localhost.

**Comment by Xiphoseer** [comment]
This is such a bad issue description, please improve that, or the issue will be closed. The expressions "Connecting CMD to your localhost" and "do localhost" clearly indicate, you should first start to learn about what a web server is, and how it works, before attempting to work with software such as this.

**Comment by Egmo23** [comment]
Basically, I type in localhost, and there is no password, and root. I'm hosting my server from my computer, and I've got XAMPP. But the issue is, it says that the connection was refused, and I typed in everything right.

**Comment by Egmo23** [comment]
I'm typing all the details right, including the database name, which is luni.

**Comment by Xiphoseer** [comment]
Where do you type that into??? The Install Screen of the CMS?

**Comment by Egmo23** [comment]
The setup for the CMS, Here is the link: http://luremastered.prohosts.org/UniverseLauncher-272b43de13ca837105f09237b2c29cfa58715971/?page=dashboard

**Comment by Xiphoseer** [comment]
I hope you realize, you need to run XAMPP and the web server on the same machine, which is very unlikely that you do when using a hosting provider such as prohosts.org

**Comment by Egmo23** [comment]
Ohh.. Is there any other web hosting providers that actually allow this?

**Comment by Xiphoseer** [comment]
hmmm none that I know, it would certainly be a paid service and would need to run a Windows VPS with XAMPP and LUNI server. It's theoretically possible to set up the server on your computer and database and the CMS with prohosts, but that would mean every query from the server to the database would need to go over the internet, which would make the server very slow.

**Comment by Xiphoseer** [comment]
Ok, I STRONGLY advise you to not try to set this up on your own, since it's neither useful nor are you qualified to run such a server successfully. End of Story!
